In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Column Description

| **Column Name** | **Description**                                                                                           |
| --------------- | --------------------------------------------------------------------------------------------------------- |
| **Index**       | Unique serial number assigned to each property.                                                           |
| **Title**       | Short title or headline describing the property listing.                                                  |
| **Description** | Detailed textual description of the property and its features.                                            |
| **Amount**      | Total listed price of the property.                                                                       |
| **Price**       | Price per square foot of the property.                                                                    |
| **Location**    | City or locality where the property is located.                                                           |
| **Carpet Area** | Actual usable floor area inside the property, measured in square feet (sq ft) or square yards (sq yd).    |
| **Status**      | Indicates whether the property is ready for immediate occupancy or is under construction.                 |
| **Floor**       | Floor number on which the property is located.                                                            |
| **Transaction** | Indicates whether the property is a new property or a resale.                                             |
| **Furnishing**  | Furnishing status of the property (e.g., Furnished, Semi-Furnished, Unfurnished).                         |
| **Facing**      | Direction the property's main entrance or balcony faces (e.g., North, South, East, West).                 |
| **Overlooking** | Primary view from the property, such as a park, garden, pool, or main road.                               |
| **Society**     | Name of the residential society or apartment complex where the property is located.                       |
| **Bathroom**    | Total number of bathrooms in the property.                                                                |
| **Balcony**     | Total number of balconies available in the property.                                                      |
| **Car Parking** | Number of dedicated parking spaces available for vehicles.                                                |
| **Ownership**   | Type of legal ownership, such as Freehold or Cooperative Society.                                         |
| **Super Area**  | Total saleable area, including the carpet area, wall thickness, and a proportional share of common areas. |
| **Dimensions**  | Physical dimensions of the property (e.g., length × width).                                               |
| **Plot Area**   | Total land area occupied by the property.                                                                 |

In [34]:
house_df = pd.read_csv('../datasets/house_prices.zip')
house_copy = house_df.copy()

In [35]:
columns = house_copy.columns
columns = pd.Series(columns.str.split('(').str.get(0).str.strip().str.lower().str.split(' ')).apply(lambda x : '_'.join(x))
house_copy.columns = columns
columns
house_copy.drop('index', axis= 1, inplace= True)

# Data Cleaning

### Messy Data

- Extra index column is given.

- Two informations are in the same column Title which are number of bedrooms and location.

- The phrase `BHK Ready to Occupy Flat for Sale` is common in every value of the column Title.

- Description has 5 major informations number of bedrooms, precise area, price, commercials and whether it is furnished, semi-funished or unfurnished.

- Location has two informations total floors in buildings and on which floor flat is located.

- 63% of data is duplicated.

### Dirty Data

- Some column names are lower case and some are capitalize. `consisttency`

- Some of the values are same in Title and Description column. `uniqueness`

- Amount column has dtype string and inconsistent units. `inconsistency`

- Description, Price, Location, Status, facting, overlooking, society, balcony, car parking, ownership and has missing values. `completeness`

- Carpet Area and Super Area column has inconsitent units and missing values. `incosnistency` and `completeness`

- Dimensions and Plot Area has all values missing. `completeness`

- Bathroom and Balcony has dtype string instead of integer. `invalid`


#### Quality Dimensions Solution:
1. Uniqueness
2. Completeness
3. Tidiness
4. Validity
5. Accuracy 
6. Consistency

In [36]:
house_copy.head()

,title,description,amount,price,location,carpet_area,status,floor,transaction,furnishing,facing,overlooking,society,bathroom,balcony,car_parking,ownership,super_area,dimensions,plot_area
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [37]:
house_copy.shape

(187531, 20)

In [38]:
house_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 20 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   title        187531 non-null  str
 1   description  184508 non-null  str
 2   amount       187531 non-null  str
 3   price        169866 non-null  float64
 4   location     187531 non-null  str
 5   carpet_area  106858 non-null  str
 6   status       186916 non-null  str
 7   floor        180454 non-null  str
 8   transaction  187448 non-null  str
 9   furnishing   184634 non-null  str
 10  facing       117298 non-null  str
 11  overlooking  106095 non-null  str
 12  society      77853 non-null   str
 13  bathroom     186703 non-null  str
 14  balcony      138596 non-null  str
 15  car_parking  84174 non-null   str
 16  ownership    122014 non-null  str
 17  super_area   79846 non-null   str
 18  dimensions   0 non-null       float64
 19  plot_area    0 non-null       float64
dtypes: float64(3), str(17)
memory usage: 28.6 MB

In [39]:
house_copy.describe()

              price  dimensions  plot_area
count  1.698660e+05         0.0        0.0
mean   7.583772e+03         NaN        NaN
std    2.724171e+04         NaN        NaN
min    0.000000e+00         NaN        NaN
25%    4.297000e+03         NaN        NaN
50%    6.034000e+03         NaN        NaN
75%    9.450000e+03         NaN        NaN
max    6.700000e+06         NaN        NaN

In [40]:
house_copy.duplicated().sum()

np.int64(119339)

In [41]:
house_copy.duplicated().sum() / len(house_copy) * 100

np.float64(63.63694535836741)

In [42]:
location = house_copy['location'].value_counts()
location.index

Index(['new-delhi', 'bangalore', 'kolkata', 'gurgaon', 'ahmedabad',
       'hyderabad', 'chennai', 'jaipur', 'greater-noida', 'faridabad',
       'vadodara', 'surat', 'pune', 'thane', 'mumbai', 'visakhapatnam',
       'mohali', 'zirakpur', 'chandigarh', 'noida', 'goa', 'ranchi', 'bhiwadi',
       'kochi', 'dehradun', 'ghaziabad', 'lucknow', 'kanpur', 'patna',
       'guwahati', 'sonipat', 'coimbatore', 'navi-mumbai', 'nagpur',
       'jamshedpur', 'kalyan', 'vijayawada', 'palghar', 'raipur',
       'bhubaneswar', 'agra', 'aurangabad', 'mangalore', 'badlapur',
       'siliguri', 'panchkula', 'nashik', 'guntur', 'varanasi', 'thrissur',
       'trivandrum', 'allahabad', 'ernakulam', 'haridwar', 'mysore',
       'durgapur', 'gwalior', 'ludhiana', 'vapi', 'indore', 'bhopal',
       'jabalpur', 'trichy', 'udaipur', 'bhiwandi', 'rajahmundry', 'tirupati',
       'belgaum', 'jodhpur', 'kozhikode', 'satara', 'shimla', 'udupi',
       'vrindavan', 'ahmadnagar', 'madurai', 'navsari', 'nellore', 'palakkad',
       'pondicherry', 'solapur'],
      dtype='str', name='location')

In [43]:
society = house_copy['society'].value_counts()
society

society
Hamdam Apartment              1648
Malibu Town                   1158
Shree Vardhman Victoria       1154
DLF Skycourt                  1153
Nebula Tower                   982
                              ...
Sushma Capital                   1
Sushma Chandigarh Infinium       1
Silver City Greens               1
Nirmaan Royale Empire            1
Jaivee Radha Enclave             1
Name: count, Length: 10376, dtype: int64

In [44]:
house_copy['ownership'].value_counts()

ownership
Freehold                112229
Leasehold                 5285
Co-operative Society      3431
Power Of Attorney         1069
Name: count, dtype: int64